CREATE TABLE IF NOT EXISTS `message` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	`enable` BOOLEAN NOT NULL DEFAULT FALSE,
	`text` VARCHAR(256) NULL,
	periodicity INTEGER NULL
);

CREATE TABLE IF NOT EXISTS `humeur` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	`enable` BOOLEAN NOT NULL DEFAULT TRUE,
	`text` VARCHAR(256) NULL
);
