
CREATE TABLE IF NOT EXISTS `configuration` (
	`key` VARCHAR(32) PRIMARY KEY,
	`value` VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS `game_bundle` (
	id INTEGER PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	json VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS `humeur` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	`enable` BOOLEAN NOT NULL DEFAULT TRUE,
	`text` VARCHAR(256) NULL
);

CREATE TABLE IF NOT EXISTS `message` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	`enable` BOOLEAN NOT NULL DEFAULT FALSE,
	`text` VARCHAR(256) NULL,
	periodicity INTEGER NULL
);

